---
swagger: 2.0
info:
  title: Assessment
  description: Pathfinder Assessment API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
paths:
  /customers/{custId}:
    get:
      description: Get Customer
      responses:
        200:
          description: Customer Details
          schema:
            $ref: '#/definitions/CustomerType'
        404:
          description: Customer Not Found
    parameters:
    - name: custId
      in: path
      description: Customer Identifier
      required: true
      type: string
  /customers/{custId}/applications/{appId}:
    get:
      description: Get Application details
      responses:
        200:
          description: Application Details
          schema:
            $ref: '#/definitions/ApplicationType'
        404:
          description: Application Not Found
    parameters:
    - name: custId
      in: path
      description: Customer Identifier
      required: true
      type: string
    - name: appId
      in: path
      description: Application Identifier
      required: true
      type: string
  /customers/:
    get:
      description: Get Customers
      responses:
        200:
          description: Customers Details
          schema:
            type: array
            items:
              $ref: '#/definitions/CustomerType'
    post:
      description: Create Customer
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CustomerType'
      responses:
        200:
          description: Customer Created
          schema:
            type: string
        400:
          description: Unable to create customer
  /customers/{custId}/applications/:
    get:
      description: Get applications list
      responses:
        200:
          description: Applications List
          schema:
            type: array
            items:
              $ref: '#/definitions/ApplicationType'
    post:
      description: Create Application
      parameters:
      - name: custId
        in: path
        description: Customer Identifier
        required: true
        type: string
      - name: body
        in: body
        description: Application Definition
        schema:
          $ref: '#/definitions/ApplicationType'
      responses:
        200:
          description: Application Created
          schema:
            type: string
        400:
          description: Unable to create application
    parameters:
    - name: custId
      in: path
      required: true
      type: string
  /customers/{custId}/applications/{appId}/assessments:
    get:
      description: Get assessment ids
      responses:
        200:
          description: Application Assessments
          schema:
            type: array
            items:
              type: string
    post:
      description: Create Assessment
      parameters:
      - name: body
        in: body
        description: Application Assessment
        schema:
          $ref: '#/definitions/AssessmentType'
      responses:
        200:
          description: Assessment Created
          schema:
            type: string
    parameters:
    - name: custId
      in: path
      required: true
      type: string
    - name: appId
      in: path
      required: true
      type: string
  /customers/{custId}/applications/{appId}/assessments/{assessId}:
    get:
      description: Get Application Assessment
      responses:
        200:
          description: Assessment Details
          schema:
            $ref: '#/definitions/AssessmentType'
        400:
          description: Assessment Not Found
    parameters:
    - name: custId
      in: path
      required: true
      type: string
    - name: appId
      in: path
      required: true
      type: string
    - name: assessId
      in: path
      required: true
      type: string


  /customers/{custId}/applications/{appId}/assessments/{assessId}/process:
    get:
      description: Process assessment results and return value
      responses:
        200:
          description: Assessment Results
          schema:
            $ref: '#/definitions/AssessmentProcessType'
        400:
          description: Assessment Not Found
    parameters:
    - name: custId
      in: path
      required: true
      type: string
    - name: appId
      in: path
      required: true
      type: string
    - name: assessId
      in: path
      required: true
      type: string
definitions:
  CustomerType:
    required:
    - CustomerName
    - CustomerDescription
    - CustomerAssessor
    - CustomerVertical
    properties:
      CustomerId:
        type: string
      CustomerName:
        type: string
      CustomerDescription:
        type: string
      CustomerAssessor:
        type: string
      CustomerVertical:
        type: string
      CustomerSize:
        type: string
  ApplicationType:
    required:
    - Description
    - Name
    properties:
      Id:
        description: Application Id
        type: string
      Name:
        description: Application Name
        type: string
      Description:
        description: Application Description
        type: string


  AssessmentResponse:
    description: map
    properties:
      default:
        $ref: '#/definitions/QuestionAnswer'
    additionalProperties:
      type: string

  QuestionAnswer:
    type: object
    required:
    - default
    properties:
      default:
        type: string
      additonalProperties:
        type: string

  AssessmentType:
    type: object
    required:
    - payload
    - deps
    properties:
      payload:
        $ref: '#/definitions/AssessmentResponse'
      datetime:
        type: string
      deps:
        type: array
        items:
          type: string

  AssessmentProcessType:
    required:
    - AssmentNotes
    - AssessResults
    - Dependencies
    properties:
      AssmentNotes:
         type: string
      Dependencies:
         type: array
         items:
            type: string
      AssessResults:
         type: array
         items:
            $ref: '#/definitions/AssessmentProcessQuestionResultsType'
  AssessmentProcessQuestionResultsType:
    required:
    - QuestionTag
    - QuestionAnswerDescription
    - QuestionRank
    properties:
      QuestionTag:
        type: string
      QuestionAnswerDescription:
        type: string
      QuestionRank:
        type: integer


