language: java
jdk: oraclejdk8
services:
- docker
after_success:
- export IMAGE_NAME=quay.io/noeloc/pathfinder
- docker login -u=$QUAY_USER -p=$QUAY_TOKEN quay.io
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
- docker push $IMAGE_NAME
env:
  global:
  - secure: j+qEE3INkVfltxKElwcShmOkNXSorRk2NqoME6YR4QSeoM/3QOUz/gAjdz0WDEspd+qJm1iNQBp4BFg0iSjXIeAW9aTo8akVzKvbAoK4M5kCm5Z9hh3KN7eUQfnENHWZ45goQrS2DoWtQJUb6cNnYFA05HQu7OtklZhWHXc9bNn8UAA2Zck/9YSKtg32SckPTI4aZkP6vkINmt7gn60iHm0Qt63ySkb9zy6jONjF77wSeKgG39QauO93lkyuHP8n6KW3dSy/H6g8zVvpasTLeVM4Q5wpj18Yr4hTy+5C0fIqao4d0FWryOyAGbIOrBqHvHGhmVxd6+e8pJeODiWF0bKIrjN1a+9wPW6mvQI3aiqN0u3AwK84y+UaWlVFDsNPmoAS8a4ubWxFFvC6++nae6hIiONRjU2JTACKcKZk6RBK0pti9iskjEwubQqLcxIIo7n1Ry5MzFqJrVfG7wnzuWZQi59t3tMjYhuZoM5MH3WijLr6IwXHXAE2b6IvX7JVvPvJ4xASJaPi4K30alx6TDqga6vr9ljszOlQ1rXvIiQFW6APOeyWbIarB+liPKdrKYw2MlycWdGKHB+HC9UNI5j/dJVFHzveiQ4WI8Zs2rOctbskeJ82sYragdI67bd8jIewHjgmsgYcj/3B0Mo1IF7s9oJ70y/1hS8Ey2QufOk=
  - secure: Pp6/kObQGHWiyDYg5QgxPkZyqdbTyYKzI4EIX1ubJhaH7Lf225v9NHGusWSPBBp2mKa8SYwAbyUFMgF45o83m1rdpWOnArZG20Kzl/eGAUWO4TqmhkrJ8WIgaFI9gkYuXrI+hcu0PMJjcoWiFCFpm25YgcKAFlfzSWvejTWnT/1I98t9FLxewiTZAPRvChf2QPOgymHIWH5s3Go9YdK4VDUoBNMkIs8MbYHxPe0epNhwJslSjK4g6kbN1aBiC2zCrSG/ZCdKf2iR0arLgM5Ksfo7gl+iZr+9EphAVb0uWmFwCwns5Y3WLPJikaQsyX4YbWc5XFoPao5HwplhTKVtMQ/GX28NzKlzIUrKzaveQdUxrth2jc4Ign8m/oFtvSLyX12o9qqJ/hfKIcM+Mnrq9gNihbEgP7fN8JaN4BVZ6NbfD2BI3eyKfd9+sctLQXyu0+y0Ip0b2GI8Tc32bRjSxVITmsdIjOw6SlK/Pgbe+0LAdh9uxCtaaij6+Bku1MdUmxgBq1GsHhScsaYMJ9G/LflVIfbSx8LIfO2cMmdVobUMaTqiuOYFc+1KPSfvqRIwZkAOfe1M6k4E+gjcfOJnyU2WexroBlsOcSmFpYIYJ5EIVkxBas7MJh4MfXtPHpAtIvIO8CS+d6Ti9wdKoS1vt7pO1y4ABY9FIz0vO3vFXME=
