language: java
jdk: oraclejdk8
services:
- docker
after_success:
- export IMAGE_NAME=quay.io/noeloc/pathfinder
- docker login -u=$QUAY_USER -p=$QUAY_TOKEN quay.io
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
- docker push $IMAGE_NAME
env:
  global:
  - secure: G1WIewOtwgquwKMl+lNJB2jUBZuGsvWTa1Xnmfa0su0izTk4Weoe27UwTRXgNyiO8m5/z+BAfiA2YR+J/epGJ77L4YZZUZwhWp6SozRCuUcAuA9KizLw1ZPeIRKw0OIEef2ahDc939RSowb/JhA8VeKFREP2tL6nSDcWSRNh1dRF8t1Hxl2cIbObbgNfmTHttLXsAA7cYikL1PIuGjYaj9Z/yTiysSnaW2xzDkFcWXk0pZfbbv2cbngu1qKF/gfMaJ61acWSExdXcjVeWL14bNZ/SKLDDv+A92Yz4PF9U/fJ5wV8QN5A2JG3h7OCZ5PuGHHVuDrW0U6vc9VxSEpj5U0B1JzDylRBTQL2q5rl9T9ffZBJMCKHYQ4+Ws+ieO+Ru9L0poq4Hzzg4jesm8FjpELePbb1l6vTEoWiifpO3JSqU3QJAvTdt/PuHLW/e403EGAnF8mnHWociOuvCE2eZktOYZx9fIbB1R7CFwClofDgbSposrvYAEYO9jvbDx/3rSXEfTiQ15mwC0M+ELAiPF0RwVNtmEVN9YdV8UNrnRB26vIFit/tqD6FUNCqF2XSXHWXOP+hAA0F5x9dHP/sxPxyMa3HuuIKTnQaXhqmndh0tNVqFCR/B2jm9hMGxCnTenP50/O6lPX4UyPfoouptIkbuTIyFPT6Fv9CrQCV0/0=
  - secure: M3+Yn/nNeaIeMrPP4eQ/NhC2j2IQf5YpSrH+0ifJV5TZ68vZRjYKFlhFgxxtiSMwvJabohlBI59PDgb+pAYcsLBMbx33bIZ18+d+0EkqtD7CxqXAiC5EKbiow9UEWOYQ5rxmuP7FYvxBDJIYCRPFhK57/xzjPET2STyL7+yRscWQ6PwefOEtY+I4DDqIGGNXGgVCqG9pcPlwVZKxsPh4LogV2ZQPUlH5XbAifHxMboD2jqRJjZq0ccWmwfLw0xhoenVcpi0GumUhGlU+aLCtRiCSbdt8YMdRrjxhChwTu4MogGWgLQFgF6ioHkaACABE/Ix3FLPR7g+O/OuqX2D7u5d0RtGK9i5ts47AUtFwzWlRE5a3TdS9j+TJ+lGwrkUpDjhBWqbsTW57qczpvhEZweYfWbZys5Qb5nH6rojjVW0Vq7kW7cOQh2SlPYsEYsgPg3kndDMWcOQqhnigaYRz+kJOi7XerVihQD7iXxsSqyqDbImhDybOSKP/PKWTLBImtRx+/twDdRHGmF88SvPsjYB+8dOM7mGqXgEqbjR8yF1vVrvRR9s7OWUZKTJ5eS29slbNj4PzotvR6Iti9odSn/Btlfr1P0wPrEonH6LLE7D5Hs7QURmoMoF1B0+SRGZrkgHI8LxhmQiyo8KZV6eUD7MWsbk7ASBo2Q6jeL/k6bU=
