language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: DXBCdxk6X76fw2D+NZyTAmLkAkoi7sUj7E3xejujasuZ0GbDK4Ehm0ifBuPNbrlvyIboebQwjlPKdIm+hlD6ScUxF8SeP6ZoGh7pi5u50841KzPmvBL1lfkD0uvRE4sX1Q9U9s6i2iQ2h1st6dPYIKQ43UJLj0s7uUEVFsvev+puxRvOXth08kHXTXTrqUCKtDdw3rCBCGb2j08Ac+2meZ/Yl02cZJLOjK8ra1vSAEYIKi0qImU2SQ4vOtwfAafHU+XL6oGdwN5mmEt4xpfhmhteIGVAqIFn4uGC45hVXyEw702BwemRPyRwUqAwXZC9f1Mntv+/U6d5vuONBkOxO3MfkSD94BOVXuY9uFrW8CqRENfZBnhhBPZKiAdH+jdde78O4sBrmFOY683VoVHfbauK3Eez2RfnhGTdax9n/zW5bFRdcX6Z44zYZ1pOWckHgulh739isSw9GzXUwdg3lfF/+3GBGkysOiyWATLzUmKfXkzONsSNOrz1FNwFQFt+nW5q6L/Wk92i0sZfsoeARBzOGQm/81Ze5RCLgJMFU/DnFZxyqXVWjhF/ftoO8asJWl/kOQdiygXQb5aJaljnhb3UHmMfE6ssM5jijDrg4WxZCML+URn2agpuln2sStA7xZnhWvvb0yQ2I/xi3ArL+ZzKiVK0XoTvLEtE+TdmOyw=
  - secure: WOcb1AZyrmHVYJ5qkmbhQCUNVMpPPYhsKH/d7e0GCCBhoOME+lSHjh/VntAuy1lH6A5euPIe4srxhTBL4+r1m7tzoTHhPmH6+NoQFS4ZhFiOhkA5ptOAqa4qnutPTDDyz+CgiVjA4EYwo5l75zCmZ3yQUuxDQJQUvWtlVgD+pWq+JUgyBeF0Znaxmub8tO1ZM7K8oXN6FGSiyZ9oXlhXUjUh+sOtN/IkvzErV8nQxygjdWVh13aFeoK7TXr2jek8QcIdkpGgvoUYpUKgrCAxrhfJxLEeeJfJgnwPzMnudtQV+kUHfwJyrks0EN9dGi5KpxgomAaUh8Ax1XDxdYImab9M7+0RdbAjH1/wiz6cDWFXDS8tULbOKhKoeCs1ULcNshCrm9AsCEq/rtus8ohz40GlSQHICtbqOEhEloS6mPWBY+rpVfVQG2y+C82QwLF4JXm6PopnakHbdkcAfMNngBduqM3B0DQts9vQAl2jar5XD/x16HpXj/AslOaopGxONcfeL3v7O6oKheyRnZSHZsuD6D4D98KbAAkZl22w204np3ktmtIzVGdVfNjHBl1aSmEZ47M5zkksITM5LTRBziKaoDsDNuJo21BzF9n4HGz6MNrwZBZH33mCvzYQJRbXEPn4W7W/IELbRcrLvEzIpzuvL+xwO9tBiwbPjFhEIfs=
after_success:
- export IMAGE_NAME=quay.io/noeloc/pathfinder
- docker login -u=$QUAY_USER -p=$QUAY_TOKEN quay.io
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
- docker push $IMAGE_NAME
