language: java
jdk: oraclejdk8

services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

after_success:
- export IMAGE_NAME=quay.io/noeloc/pathfinder
- docker login -u=$QUAY_USER -p=$QUAY_TOKEN quay.io
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
- docker push $IMAGE_NAME
