language: java
jdk: oraclejdk8

env:
  global:
      - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

after_success:
  - export IMAGE_NAME=pathfinder/pathfinder-server
  - docker build -t $IMAGE_NAME:$COMMIT .