apiVersion: v1
kind: Template
metadata:
  name: pathfinder-build-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: pathfinderapp
    name: pathfinderapp
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: quay.io/noeloc/pathfinder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/redhat-cop/pathfinder.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: GR_sNsobZZMP1Y-dyZOI
      type: GitHub
    - generic:
        secret: Nck0HrvzfZc9-KYRWQWN
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    labels:
      app: pathfinderapp
      build: pathfinderbinary
    name: pathfinderbinary
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: quay.io/noeloc/pathfinder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: YpRB9VsRgmlnDaG3W_YA
      type: GitHub
    - generic:
        secret: _UAzzb_wHMSWCT7fH449
      type: Generic
  status:
    lastVersion: 0